# keep your existing title/description/url/theme/minima/plugins as-is

collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page   # ensures each project renders as an HTML page

# Navbar (keep whatever you already have)
header_pages:
  - index.md
