url: "https://msunbulee.github.io"
theme: minima

# Tell Jekyll that collections live under /portfolio
collections_dir: portfolio

collections:
  projects:
    output: true
    permalink: /portfolio/_projects/:name/

defaults:
  - scope:
      path: ""          # applies globally
      type: "projects"
    values:
      layout: page      # ensures a real HTML page is rendered

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - index.md
