title: ""
description: ""
url: "https://msunbulee.github.io"
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-redirect-from   # optional; uncomment if you use redirects

# NEW: Collections
collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/

# (Optional) Defaults so you don’t repeat front matter
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page          # reuse Minima’s page layout
      nav_exclude: true     # don’t put individual projects in header nav
      toc: false

# Header nav (top bar)
header_pages:
  - index.md
  - portfolio/projects/index.md   # <- add a listing page for Projects
