# ===========================
# Site Info
# ===========================
title: ""
description: ""
url: "https://msunbulee.github.io"   # your site URL
theme: minima

# ===========================
# Minima Theme Settings
# ===========================
minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

# ===========================
# Plugins
# ===========================
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-redirect-from   # uncomment if you want redirect pages

# ===========================
# Collections
# ===========================
# Tell Jekyll where to look for collections (inside /portfolio/)
collections_dir: portfolio

collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/

# ===========================
# Defaults for Collections
# ===========================
defaults:
  - scope:
      path: ""           # applies to entire site
      type: "projects"   # applies only to items in _projects
    values:
      layout: page       # ensures each project renders as a page

# ===========================
# Header Navigation
# ===========================
header_pages:
  - index.md             # home page
  - projects.md   # optional listing page for all projects
