title: ""
description: ""
url: "https://msunbulee.github.io"
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-redirect-from   # optional; uncomment if you use `redirect_from` in pages

header_pages:
  - index.md
  # - cv.md
  # - contact.md

collections_dir: portfolio
collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
