title: ""
description: ""
url: "https://msunbulee.github.io"
baseurl: "/portfolio"     # ← ADD THIS
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Top navbar: add any project pages you want to appear in the menu
header_pages:
  - index.md
  # If you want "Research / Projects" in the top nav, add ONE of these:
  # - projects.md
  # - projects/index.md
