title: ""
description: ""
url: "https://msunbulee.github.io"
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-redirect-from   # optional

# Top navbar: add any project pages you want to appear in the menu
header_pages:
  - index.md
  # - portfolio/project_UR10e.md
  # - portfolio/project_PalmMesh.md
