title: ""
description: ""
url: "https://msunbulee.github.io"
theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/MSunbulee"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/msunbul/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jekyll-redirect-from   # optional, only if you want stub→redirect links later

# IMPORTANT: collections live under /portfolio
collections_dir: portfolio

collections:
  projects:
    output: true
    permalink: /portfolio/projects/:name/

# Ensure each project actually renders as a page
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page

# Navbar (keep or edit as you like)
header_pages:
  - index.md
